name: accounts
services:

  # Facilities
  accounts-db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: accounts
      POSTGRES_DB: accounts

  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
    environment:
      USERNAME: guest
      PASSWORD: guest

  # Services
  accounts-service:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: accounts-service/target/accounts-service-1.0.0-exec.jar
#      tags:
#        - localhost:5000/accounts/accounts-service:1.0.0
    ports:
      - 8081:8081
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on: [accounts-db, rabbit-mq]

  accounts-mailsender:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: accounts-mailsender/target/accounts-mailsender-1.0.0-exec.jar
    #      tags:
    #        - localhost:5000/accounts/accounts-mailsender:1.0.0
    ports:
      - 8083:8083
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on: [ accounts-service, rabbit-mq ]


  accounts-examiner:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: accounts-examiner/target/accounts-examiner-1.0.0-exec.jar
    #      tags:
    #        - localhost:5000/accounts/accounts-examiner:1.0.0
    ports:
      - 8082:8082
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on: [ accounts-service, accounts-mailsender, rabbit-mq ]