server:
  port: 8083

spring:
  application:
    name:  accounts-mailsender

  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.example.com
    port: 25
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth:  true
          starttls:
            enable:  true
